### ISSUE TITLE
request permission

### ISSUE THREAD

**Issue by magcode** [magcode/msem6#1]
Hello @sqozz

I'm about to improve your https://git.geekify.de/sqozz/sem6000 a bit.
I wanted to ask for permission to create a version of it and host it here in github.

my ideas:

* MQTT interface for SEM6000 (already got this working)
* read consumption values (day, month, year) as they are currently broken (already got this working)
* GNU General Public License v3.0

**Comment by sqozz** [comment]
Hey there! First of all, thank you a lot for the way you handle this - really appreciated :)

1. I think an MQTT interface is a nice feature but should live in a separate project. My version is aimed to be a library supporting all features so people can build around it however they like. Therefore building MQTT support into the library would cause dependencies which not everybody needs. If you miss features in the library to make a proper MQTT implementation feel free to suggest changes and we can do our best to provide the needed functionality.

2. Awesome that you where able to fix the broken functionality. Feel free to raise an issue or create an PR on my repo. I can understand if you don't want to create a new account just for this. So you can also point me to a branch of you and I can port the fix over if you prefer this :)

3. I'd prefer to put this code under CC0 instead of GPL. I hope I can follow up on this soon and give my code an explicit license. For the time being you've my written permission to change and use the code as long as you don't introduce a new licence :+1:

**Comment by magcode** [comment]
Hi,

thanks for your response.

1) sorry. I was not clear enough. For sure MQTT would not be part of the library. It would be another "example.py".

At the moment I stopped my python efforts in favour of a java based application.
I still have my version of  sem6000.py which I will post here. You may want to look into it and take over what makes sense.

**Comment by magcode** [comment]
There are still some debug print's ... but main point is "getTotalToday" which waits for _multiple_ notifications
[sem6000.txt](https://github.com/magcode/msem6/files/4757437/sem6000.txt)
